[window]
decorations = "None"
opacity = 0.9
startup_mode = "Fullscreen"

[font] 
normal = { family = "JetBrainsMono Nerd Font" }
size = 14

[terminal] 
shell = { program = "C:\\Windows\\System32\\wsl.exe", args = ["~"] }

[selection]
save_to_clipboard = true

[mouse]
bindings = [
  { mouse = "Right", action = "Paste" }
]

[env]
TERM = "xterm-256color"

# Colors (Gruvbox dark - from alacritty-theme on github) 
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
