theme = "tokyonight"

[editor]
cursorline = true
true-color=true

[editor.cursor-shape]
insert = "bar"   

[editor.statusline]
left =  ["version-control", "file-name", "file-type", "file-encoding", "read-only-indicator", "file-modification-indicator"]
center = ["mode", "spinner"]
right =  ["diagnostics", "selections", "register", "position", "position-percentage" ]

[keys.insert]
j = { k = "normal_mode" }


