return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  dependencies = {
    "nvim-tree/nvim-web-devicons",
    "windwp/nvim-ts-autotag",
    "andymass/vim-matchup",
  },
  ft = {
    "htm",
    "html",
    "md",
    "xml",
    "sh",
    "dockerfile",
    "go",
    "csv",
    "css",
    "js",
    "json",
    "lua",
    "md",
    "sql",
    "toml",
    "nvim",
    "vim",
    "yaml",
  },
  lazy = true,
  config = function()
    local configs = require("nvim-treesitter.configs")

    configs.setup({
      ensure_installed = {
        "bash",
        "css",
        "csv",
        "dockerfile",
        "go",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "query",
        "regex",
        "rust",
        "sql",
        "vim",
        "vimdoc",
        "yaml",
      },
      matchup = {
        enable = true,
      },
      autotag = { enable = true },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
}
